// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef ui_h
#define ui_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include "MyWindow.h"
#include <FL/Fl_Check_Button.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_Text_Display.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Value_Input.H>
#include <FL/Fl_Choice.H>
#include <FL/Fl_Spinner.H>

class UserInterface {
public:
  UserInterface();
  Fl_Window *Mywindow;
  MyWindow *viewing;
  Fl_Check_Button *Line;
private:
  inline void cb_Line_i(Fl_Check_Button*, void*);
  static void cb_Line(Fl_Check_Button*, void*);
public:
  Fl_Check_Button *Circle;
private:
  inline void cb_Circle_i(Fl_Check_Button*, void*);
  static void cb_Circle(Fl_Check_Button*, void*);
  inline void cb_Clear_i(Fl_Button*, void*);
  static void cb_Clear(Fl_Button*, void*);
public:
  Fl_Check_Button *Polyline;
private:
  inline void cb_Polyline_i(Fl_Check_Button*, void*);
  static void cb_Polyline(Fl_Check_Button*, void*);
  inline void cb_Show_i(Fl_Button*, void*);
  static void cb_Show(Fl_Button*, void*);
  static Fl_Menu_Item menu_[];
  inline void cb_Exit_i(Fl_Menu_*, void*);
  static void cb_Exit(Fl_Menu_*, void*);
  inline void cb_Simple_i(Fl_Menu_*, void*);
  static void cb_Simple(Fl_Menu_*, void*);
  inline void cb_Sample_i(Fl_Menu_*, void*);
  static void cb_Sample(Fl_Menu_*, void*);
  inline void cb_Bowtie_i(Fl_Menu_*, void*);
  static void cb_Bowtie(Fl_Menu_*, void*);
  inline void cb_House_i(Fl_Menu_*, void*);
  static void cb_House(Fl_Menu_*, void*);
  inline void cb_Simple1_i(Fl_Menu_*, void*);
  static void cb_Simple1(Fl_Menu_*, void*);
  inline void cb_Sample1_i(Fl_Menu_*, void*);
  static void cb_Sample1(Fl_Menu_*, void*);
  inline void cb_Polygon1_i(Fl_Menu_*, void*);
  static void cb_Polygon1(Fl_Menu_*, void*);
  inline void cb_Polygon2_i(Fl_Menu_*, void*);
  static void cb_Polygon2(Fl_Menu_*, void*);
  inline void cb_Color_i(Fl_Menu_*, void*);
  static void cb_Color(Fl_Menu_*, void*);
  inline void cb_Style_i(Fl_Menu_*, void*);
  static void cb_Style(Fl_Menu_*, void*);
public:
  Fl_Check_Button *Polygon;
private:
  inline void cb_Polygon_i(Fl_Check_Button*, void*);
  static void cb_Polygon(Fl_Check_Button*, void*);
public:
  Fl_Window *OutputWindow;
  Fl_Text_Display *OutputTextDisplay;
private:
  inline void cb_Clear1_i(Fl_Button*, void*);
  static void cb_Clear1(Fl_Button*, void*);
public:
  Fl_Check_Button *PrintToggle;
private:
  inline void cb_PrintToggle_i(Fl_Check_Button*, void*);
  static void cb_PrintToggle(Fl_Check_Button*, void*);
public:
  Fl_Window *SimpleLineWindow;
  Fl_Value_Input *StartX;
  Fl_Value_Input *StartY;
  Fl_Value_Input *EndX;
  Fl_Value_Input *EndY;
  Fl_Button *SetEndLine;
private:
  inline void cb_SetEndLine_i(Fl_Button*, void*);
  static void cb_SetEndLine(Fl_Button*, void*);
  inline void cb_Reset_i(Fl_Button*, void*);
  static void cb_Reset(Fl_Button*, void*);
public:
  Fl_Window *SimpleCircleWindow;
  Fl_Value_Input *CircleX;
  Fl_Value_Input *CircleY;
  Fl_Value_Input *CircleR;
private:
  inline void cb_Draw_i(Fl_Button*, void*);
  static void cb_Draw(Fl_Button*, void*);
  inline void cb_Reset1_i(Fl_Button*, void*);
  static void cb_Reset1(Fl_Button*, void*);
public:
  Fl_Window *ColorWindow;
  Fl_Choice *ColorDropdown;
private:
  inline void cb_ColorDropdown_i(Fl_Choice*, void*);
  static void cb_ColorDropdown(Fl_Choice*, void*);
public:
  Fl_Value_Input *ValueRed;
private:
  inline void cb_ValueRed_i(Fl_Value_Input*, void*);
  static void cb_ValueRed(Fl_Value_Input*, void*);
public:
  Fl_Value_Input *ValueGreen;
private:
  inline void cb_ValueGreen_i(Fl_Value_Input*, void*);
  static void cb_ValueGreen(Fl_Value_Input*, void*);
public:
  Fl_Value_Input *ValueBlue;
private:
  inline void cb_ValueBlue_i(Fl_Value_Input*, void*);
  static void cb_ValueBlue(Fl_Value_Input*, void*);
public:
  Fl_Button *ButtonSetColor;
private:
  inline void cb_ButtonSetColor_i(Fl_Button*, void*);
  static void cb_ButtonSetColor(Fl_Button*, void*);
public:
  Fl_Window *StyleWindow;
  Fl_Spinner *ThicknessSpinner;
private:
  inline void cb_ThicknessSpinner_i(Fl_Spinner*, void*);
  static void cb_ThicknessSpinner(Fl_Spinner*, void*);
public:
  Fl_Choice *LineStyleDropdown;
private:
  inline void cb_LineStyleDropdown_i(Fl_Choice*, void*);
  static void cb_LineStyleDropdown(Fl_Choice*, void*);
public:
  void show();
};
#endif
